### ISSUE TITLE
Where should I put my mail & pass?

### ISSUE THREAD

**Issue by ghost** [fstachura/email-bot#1]
In your `example-config.json`, there's no **mail** option.It's not clear. 

Should I put my mail there (on login) with pass on password?

If I have two destination mail, where should i put the pass? It will not auto detect by itself, right?

```
{
    "mailbox": {
        "server": "",
        "port": 143,
        "login": "email-bot",
        "password": ""
    },
    "destinations": {
        "rcpt1@example.com": "https://discord.com/api/webhooks/id/token",
        "rcpt2@example.com": "https://discord.com/api/webhooks/id2/token2"
    },
    "default_destination": "https://discord.com/api/webhooks/id3/token3"
}
```

**Comment by fstachura** [comment]
Hi @backermanbd 

I'm not really sure what you mean by "mail option". The script only uses IMAP, therefore it needs the IMAP login. It's often the same as the email of the mailbox, but not always. The email/login should be put in mailbox.login, the password in should be put in mailbox.password.

> If I have two destination email

Again, I'm not sure what you mean. The script only forwards messages received by a single IMAP account to different discord-compatible webhooks based on the recipient field in the received email.
The main usecase looks like this: you have a single mailbox, that receives messages forwarded from multiple email accounts. These forwarded messages will usually (but not always, if the recipient was in BCC) contain email address of the original recipient in the "To" field. The value of that field is used to choose the webhook address from the "destinations" object.

As I mentioned, this unfortunately doesn't work for messages where the recipient was in the BCC field. In such a case, the default_destination will most likely be picked.

Multiple mailboxes are not supported at all, this is a very simple script.

**Comment by ghost** [comment]
Sorry for troubling you. I'm new at this.

IMAP username in `login`, right?

Does it look like this? I've double-quoted the port value.
```
{
    "mailbox": {
        "server": "imap.google.com",
        "port": "993",
        "login": "dummy@gmail.com",
        "password": "12345"
    },
}
```

**Comment by fstachura** [comment]
Yes, this looks correct. I have pushed a fix allows connections to Gmail accounts. Also, remember that Gmail does not allow to login over IMAP with a Google password, you need to create an app password for that. https://support.google.com/accounts/answer/185833

**Comment by ghost** [comment]
Thank you. This clarifies my doubt.
