### ISSUE TITLE
Emails with more than 1000/2000 chars don't get forwarded

### ISSUE THREAD

**Issue by ghost** [fstachura/email-bot#5]
Though the terminal message shows that mail (over 1000 chars) was forwarded to Discord, in reality, It doesn't get forwarded.

**Comment by fstachura** [comment]
Discord message length is limited to 2000 characters. If you increased the message length limits in the bot, then I suspect that the message is simply too long. Note that the title counts into the message length too - this is why I limit message contents length to 1000 characters, although that probably is a bit too careful. 

I have pushed a commit that increases the message length limits and prints the response received by the webhook request (if there is any). 
If messages still aren't forwarded, look for a line similar to the following in the standard output. It should explain why Discord discarded the message. 

> INFO:email-bot:subject test, **response from webhook**: {'content': ['Must be 2000 or fewer in length.']}

**Comment by ghost** [comment]
Thank you. This clears my doubts.

Can I increase the body text to **1700** char?

from 100
subject 200
text 1700

**Comment by fstachura** [comment]
That won't leave enough space for formatting, you need to subtract ~50 characters from something.

**Comment by ghost** [comment]
Oh, I get it now. Awesome.
